export const board = [
  {
    name: "Vedant Agarwal",
    designation: "President",
    image: "/people/vedant-agarwal.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Suhani Patel",
    designation: "Vice President",
    image: "/people/suhani-patel.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Samriddhi Mishra",
    designation: "General Secretary",
    image: "/people/samriddhi-mishra.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Aayushman Jain",
    designation: "Treasurer",
    image: "/people/aayushman-jain.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Nishant Dahiya",
    designation: "Operational Secretary (?)",
    image: "/people/nishant-dahiya.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Nihar Madhekar",
    designation: "Quant & Algo Trading Head",
    image: "/people/nihar-madhekar.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Debarun Karmakar",
    designation: "Finance & Banking Head",
    image: "/people/debarun-karmakar.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Suhani Patel",
    designation: "Blockchain & Web3 Head",
    image: "/people/suhani-patel.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Sujai",
    designation: "Cybersecurity Head",
    image: "/people/sujai.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Abhuday Singh",
    designation: "Data Analysis & ML Head",
    image: "/people/abhuday-singh.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Pranav G Nayak",
    designation: "Fullstack Development Head",
    image: "/people/pranav-g-nayak.jpg",
    email: "pranavgnayak@gmail.com",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Ayush Das",
    designation: "Public Relations Head",
    image: "/people/ayush-das.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Aditya Sharma",
    designation: "Social Media & Graphic Design Head",
    image: "/people/aditya-sharma.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
];
