export const board = [
  {
    name: "Vedant Agarwal",
    designation: "President",
    image: "/people/vedant-agarwal.jpg",
    email: "vedant.agarwal312@gmail.com",
    linkedin: "https://www.linkedin.com/in/vedant-agarwal312/",
    instagram: "",
  },
  {
    name: "Suhani Patel",
    designation: "Vice President",
    image: "/people/suhani-patel.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Samriddhi Mishra",
    designation: "General Secretary",
    image: "/people/samriddhi-mishra.jpg",
    email: "mishrasamriddhi@gmail.com",
    linkedin: "https://www.linkedin.com/in/samriddhi-mishra-a31166284/",
    instagram: "",
  },
  {
    name: "Aayushman Jain",
    designation: "Treasurer",
    image: "/people/aayushman-jain.jpg",
    email: "aayush17sty@gmail.com",
    linkedin: "https://www.linkedin.com/in/aayushman-jain-032940267/",
    instagram: "",
  },
  {
    name: "Nishant Dahiya",
    designation: "Head of Operations",
    image: "/people/nishant-dahiya.jpg",
    email: "dahiyanishant2405@gmail.com",
    linkedin: "https://www.linkedin.com/in/nishant-dahiya-3a071424b/",
    instagram: "",
  },
  {
    name: "Nihar Madhekar",
    designation: "Quant & Algo Trading Head",
    image: "/people/nihar-madhekar.jpg",
    email: "",
    linkedin: "",
    instagram: "",
  },
  {
    name: "Debarun Karmakar",
    designation: "Finance & Banking Head",
    image: "/people/debarun-karmakar.jpg",
    email: "debarun.karmakar.dsk@gmail.com",
    linkedin: "https://www.linkedin.com/in/debarunkarmakar/",
    instagram: "",
  },
  {
    name: "Mohammed Hadi",
    designation: "Blockchain & Web3 Head",
    image: "/people/mohammed-hadi.jpg",
    email: "mhdhadiabdullah@gmail.com",
    linkedin: "https://www.linkedin.com/in/mohammed-hadi-ab1820251/",
    instagram: "",
  },
  {
    name: "Sujai Murali",
    designation: "Cybersecurity Head",
    image: "/people/sujai.jpg",
    email: "velociper5@gmail.com",
    linkedin: "https://www.linkedin.com/in/sujai-murali-28a88331a/",
    instagram: "",
  },
  {
    name: "Abhuday Singh",
    designation: "Data Analysis & ML Head",
    image: "/people/abhuday-singh.jpg",
    email: "abhuday2656@gmail.com",
    linkedin: "https://www.linkedin.com/in/kunwar-abhuday-singh-280836284/",
    instagram: "",
  },
  {
    name: "Pranav G Nayak",
    designation: "Fullstack Development Head",
    image: "/people/pranav-g-nayak.jpg",
    email: "pranavgnayak@gmail.com",
    linkedin: "https://www.linkedin.com/in/pranav-g-nayak-a68101146/",
    instagram: "",
  },
  {
    name: "Ayush Das",
    designation: "Public Relations Head",
    image: "/people/ayush-das.jpg",
    email: "ayush.das0213@gmail.com",
    linkedin: "https://www.linkedin.com/in/d-ayush/",
    instagram: "",
  },
  {
    name: "Aditya Sharma",
    designation: "Social Media & Graphic Design Head",
    image: "/people/aditya-sharma.jpg",
    email: "adityasharma.variable@gmail.com",
    linkedin: "https://www.linkedin.com/in/aditya-sharma-4aa716336/",
    instagram: "",
  },
];
